'Chest X-ray' : ['A','D'],
'Hip X-ray' : ['D'],
'Limb X-ray' : ['D'],
'Abdominal X-ray' : ['D'],
'Lumbar Puncture' : ['A'],
'Electrocardiogram' : ['B','C'],
'Take bloods' : ['A','B','C','D'],
'Send a urine sample' : ['A','B','C','D'],
'Send a sputum sample' : ['A','B','C','D'],
'Send a stool sample'',' : ['A','B','C','D'],
'Take and send a swab' : ['A','B','C','D'],
'Document allergies' : ['A','B','C','D'],
'Place a cannula' : ['A','B','C'],
'Place a catheter' : ['A','C'],
'Place a chest drain' : ['A'],
'Place an abdominal drain' : ['A'],
'Give IV fluids' : ['C'],
'Give oxygen' : ['B','C'],
'Give electrolytes' : ['B','C'],
'Give antiarrhythmics' : ['B','C'],
'Give diuretics' : ['B','C'],
'Give antibiotics' : ['B','C'],
'Give nasal medications' : ['C'],
'Give pain relief' : ['C'],
'Sedate the patient' : ['A','B'],
'Intubate the patient' : ['A'],
'CT Scan' : ['D'],
'MRI Scan' : ['D'],
'Ultrasound Scan' : ['A','D'],
'Cardioversion' : ['B'],
'Thrombolysis' : ['B'],
'Prep for Theatre' : ['C'],
'Neurovascular Status' : ['B','C'],
'Wound Dressing' : ['C'],
'Patient Education' : ['A','B','C','D'],
'Prescribe Medications' : ['A','B'],
'Review Medications' : ['A','B'],
'Write Fluid Orders' : ['A','B'],
'Manual Handling' : ['C','D']